[package]
name = "data_marketplace_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.11.1"
ic-cdk-macros = "0.6.10"
serde = { version = "1.0", features = ["derive"] }
candid = "0.9"

